### ISSUE TITLE
Text hightlight needs tweaking :D

### ISSUE THREAD

**Issue by ludasmokva** [ignacionelson/dreamweaver-wombat#1]
Great theme. Really like the colour combos. But your greyish highlight which works fine on most text, obliterates text that is in grey. It doesn't 'reverse' as highlighters tend to do. This is particularly noticeable on comment text as that text is in a very similar grey. So instead of highlighting the text, it looks like it paints over it making it impossible to read the text that was highlighted. 
Please fix as otherwise a great theme.

**Comment by ignacionelson** [comment]
Thanks for the comments!
Brackets itself doesn't reverse the color of the selected text. So the gray background is the one I found most comfortable by testing on css, js, php and html code. Only comments seems to get "lost". I'll try to find something else!

**Comment by ludasmokva** [comment]
Maybe a combination of darkening or re-colouring comment text and tweaking opacity or lightening of the selector. Be careful though... there was another awesome theme (Glacier) whose selector colour was practically invisible. I couldn't even tell if any text was selected. So the exact opposite.
It's funny... the two of you have my two favourite themes and I can't use either because of the same issue - but opposite extremes. :)
In any case, I'm sure hoping something can be figured out. I would hate all that wonderful creativity to be undermined by such a small detail.
Let me know if there is anything I can do - otherwise, looking forward to the fix!

**Comment by ignacionelson** [comment]
Please check the latest update, I believe this fixes the problem. At least on the languages I've tried, everything is very readable (php, html, css, js).

Let me know how it went for you please!
Thanks!!

--

By the way, I've just reproduced what dreamweaver's designers did with wombat, no creativity from my side on this theme :P

**Comment by ludasmokva** [comment]
Awesome! Great improvement.
Thank you so much for doing it so quickly. It looks great.
As for your questioning your creativity, I have two comments:
1. You know the saying "Imitation is the greatest form of flattery"? I would suggest that recognizing what should or deserves to be imitated is also a part of creativity. And you have chosen well; and 
2. You've just improved upon an existing (and probably very popular) theme. That's all you. So take a bow. ;)

Thanks again.
